version: "3"
services:
  web:
    build:
      context: ./reactjs/demo
      dockerfile: Dockerfile
    image: my_react
    container_name: c1
    ports:
      - 8888:80
      
  nodejs:
    build: ./nodejs
    image: my_node
    ports:
      - 3000:3000