version: "3"
volumes:
  demo:

services:
  db:
    image: postgres
    volumes:
      - ./demo:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=value

  web:
    build:
      context: ./reactjs/demo
      dockerfile: Dockerfile
    image: my_react
    container_name: c1
    ports:
      - 8888:80
      
  nodejs:
    build: ./nodejs
    image: my_node
    ports:
      - 3000:3000